controller_manager:
  ros__parameters:
    update_rate: 1000
    # use_sim_time: true

    drive_module_steering_angle_controller:
      type: position_controllers/JointGroupPositionController

    drive_module_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

drive_module_steering_angle_controller:
  ros__parameters:
    joints:
    - joint_chassis_to_steering_left_front
    - joint_chassis_to_steering_left_rear
    - joint_chassis_to_steering_right_rear
    - joint_chassis_to_steering_right_front

drive_module_velocity_controller:
  ros__parameters:
    joints:
    - joint_steering_to_wheel_left_front
    - joint_steering_to_wheel_left_rear
    - joint_steering_to_wheel_right_rear
    - joint_steering_to_wheel_right_front
    # publish_rate: 50.0

    # base_frame_id: base_link

  